// WALTZ video-first exercise demo system.
// Production exercise clips can be added to /videos and mapped below.
// Until then, the player shows a polished anatomical reference panel instead of the old SVG mannequin.

const WALTZ_DEMOS = {
  "Barbell Bench Press": { primary:["Chest"], activation:["Triceps","Front delts"], how:["Lie with eyes under the bar and plant both feet.","Lower the bar under control toward mid-chest.","Keep shoulder blades set and wrists stacked.","Press up until the arms are straight without bouncing."] },
  "Incline Dumbbell Press": { primary:["Upper chest"], activation:["Triceps","Front delts"], how:["Set the bench to a low incline and brace your upper back.","Start dumbbells beside the upper chest.","Press up and slightly inward.","Lower slowly until elbows are just below the torso."] },
  "Cable Fly": { primary:["Chest"], activation:["Front delts"], how:["Stand tall with a slight forward lean.","Keep a soft bend in the elbows.","Bring the handles together in front of the chest.","Return slowly until the chest is comfortably stretched."] },
  "Push-Up": { primary:["Chest"], activation:["Triceps","Core"], how:["Set hands slightly wider than shoulders.","Keep head, hips and heels in one line.","Lower the chest toward the floor with elbows controlled.","Push the floor away to return to the top."] },
  "Lat Pulldown": { primary:["Lats"], activation:["Biceps","Upper back"], how:["Grip the bar just outside shoulder width.","Keep the chest tall and ribs controlled.","Pull elbows down toward your sides.","Return the bar overhead without shrugging."] },
  "Seated Cable Row": { primary:["Mid back","Lats"], activation:["Biceps","Rear delts"], how:["Sit tall with a neutral spine.","Start with shoulders relaxed and arms long.","Drive elbows back and squeeze the shoulder blades.","Return under control without rounding forward."] },
  "Chest-Supported Row": { primary:["Upper back"], activation:["Lats","Biceps"], how:["Keep the chest supported and neck neutral.","Let the arms reach fully at the bottom.","Pull elbows back beside the torso.","Pause briefly, then lower slowly."] },
  "Straight-Arm Pulldown": { primary:["Lats"], activation:["Core","Triceps"], how:["Stand tall with arms nearly straight overhead.","Brace your core and keep elbows softly bent.","Sweep the bar down toward the thighs.","Return overhead without losing torso position."] },
  "EZ-Bar Curl": { primary:["Biceps"], activation:["Forearms"], how:["Stand tall with elbows close to your sides.","Curl the bar without swinging the torso.","Squeeze the biceps near the top.","Lower until the elbows are almost fully straight."] },
  "Incline Dumbbell Curl": { primary:["Biceps"], activation:["Forearms"], how:["Lean back against the bench with arms hanging long.","Keep upper arms behind the torso.","Curl without moving the shoulders forward.","Lower slowly to a full stretch."] },
  "Hammer Curl": { primary:["Brachialis","Biceps"], activation:["Forearms"], how:["Hold dumbbells with palms facing each other.","Keep elbows fixed beside the torso.","Curl without rotating the wrists.","Lower slowly to the starting position."] },
  "Rope Pushdown": { primary:["Triceps"], activation:["Forearms"], how:["Pin elbows beside your ribs.","Press the rope down by straightening the elbows.","Separate the rope slightly at the bottom.","Return only as far as you can keep elbows still."] },
  "Overhead Cable Extension": { primary:["Triceps"], activation:["Core"], how:["Brace your ribs and keep elbows pointing forward.","Start with hands behind the head.","Straighten the elbows overhead.","Lower under control without flaring the elbows."] },
  "Assisted Dip": { primary:["Triceps","Chest"], activation:["Front delts"], how:["Keep shoulders down and chest slightly forward.","Lower by bending the elbows under control.","Stop before the shoulders roll forward.","Press through the handles to return to the top."] },
  "Seated Dumbbell Shoulder Press": { primary:["Shoulders"], activation:["Triceps","Upper chest"], how:["Sit tall with ribs stacked over the pelvis.","Start dumbbells around shoulder height.","Press overhead without over-arching the back.","Lower until elbows return just below shoulder level."] },
  "Cable Lateral Raise": { primary:["Side delts"], activation:["Upper traps"], how:["Stand tall and keep the working elbow softly bent.","Raise the arm out to the side.","Stop around shoulder height.","Lower slowly without leaning or swinging."] },
  "Reverse Pec Deck": { primary:["Rear delts"], activation:["Upper back"], how:["Keep chest supported and shoulders down.","Open the arms out and back in a wide arc.","Lead with the elbows rather than the hands.","Return slowly until the rear delts are stretched."] },
  "Face Pull": { primary:["Rear delts","Upper back"], activation:["Biceps","Rotator cuff"], how:["Set the rope around face height.","Pull toward the forehead while spreading the rope.","Finish with elbows high and shoulder blades back.","Return under control without shrugging."] },
  "Barbell Hip Thrust": { primary:["Glutes"], activation:["Hamstrings","Core"], how:["Set the upper back against the bench and feet flat.","Tuck the ribs and brace the core.","Drive through the heels until hips are fully extended.","Lower the hips under control without over-arching the back."] },
  "Bulgarian Split Squat": { primary:["Glutes","Quads"], activation:["Hamstrings","Core"], how:["Place the rear foot on a bench and set the front foot firmly.","Lower the back knee while keeping the front foot planted.","Let the torso lean slightly forward for glute emphasis.","Drive through the front foot to stand."] },
  "Cable Kickback": { primary:["Glutes"], activation:["Hamstrings","Core"], how:["Brace your torso and keep the standing knee soft.","Drive the working leg back from the hip.","Keep the pelvis square and avoid arching the low back.","Return slowly until the hip is neutral."] },
  "Hip Abduction": { primary:["Glute medius"], activation:["Glutes"], how:["Sit tall and brace lightly.","Press the knees outward against the pads.","Pause briefly at your comfortable end range.","Return slowly without letting the stack slam."] },
  "Back Squat": { primary:["Quadriceps","Glutes"], activation:["Hamstrings","Core"], how:["Set feet around shoulder width and brace your core.","Sit the hips down and slightly back while the knees track over the toes.","Keep the whole foot planted and chest controlled.","Drive through the floor to stand tall."] },
  "Leg Press": { primary:["Quadriceps","Glutes"], activation:["Hamstrings"], how:["Place the whole foot securely on the platform.","Lower the sled until the knees bend comfortably.","Keep the hips and low back against the pad.","Press through the feet without locking the knees aggressively."] },
  "Leg Extension": { primary:["Quadriceps"], activation:["Hip flexors"], how:["Align the knee with the machine pivot.","Extend the knees until the legs are nearly straight.","Squeeze the quadriceps briefly at the top.","Lower under control to the starting bend."] },
  "Romanian Deadlift": { primary:["Hamstrings","Glutes"], activation:["Back extensors","Core"], how:["Start tall with a soft bend in the knees.","Push the hips back while keeping the spine neutral.","Lower until you feel a strong hamstring stretch.","Drive the hips forward to stand without leaning back."] },
  "Seated Leg Curl": { primary:["Hamstrings"], activation:["Calves"], how:["Keep hips and back firmly against the pad.","Curl the heels down and back.","Squeeze the hamstrings at the bottom.","Return slowly until the knees are almost straight."] },
  "Lying Leg Curl": { primary:["Hamstrings"], activation:["Calves"], how:["Keep hips pressed into the bench.","Curl the heels toward the glutes.","Avoid lifting the pelvis as the knees bend.","Lower the weight slowly to full control."] },
  "Standing Calf Raise": { primary:["Calves"], activation:["Foot/ankle stabilizers"], how:["Keep knees softly straight and torso tall.","Rise onto the balls of the feet as high as comfortable.","Pause briefly at the top.","Lower the heels slowly through a full range."] },
  "Seated Calf Raise": { primary:["Calves"], activation:["Foot/ankle stabilizers"], how:["Keep the balls of the feet secure on the platform.","Raise the heels as high as comfortable.","Pause and squeeze the calves.","Lower slowly until you feel a stretch."] },
  "Cable Crunch": { primary:["Abs"], activation:["Obliques"], how:["Kneel with the rope beside the head.","Keep the hips relatively still.","Curl the ribs toward the pelvis using the abs.","Return under control without pulling only with the arms."] },
  "Hanging Knee Raise": { primary:["Lower abs"], activation:["Hip flexors","Grip"], how:["Hang tall with shoulders active.","Tuck the pelvis and lift the knees toward the chest.","Avoid swinging or using momentum.","Lower the legs slowly to the start."] },
  "Plank": { primary:["Core"], activation:["Glutes","Shoulders"], how:["Stack elbows below the shoulders.","Keep head, hips and heels in one line.","Brace the abs and squeeze the glutes.","Breathe normally while holding the position."] }
};

const WALTZ_VIDEO_URLS = {}; // Example: "Barbell Bench Press":"videos/barbell-bench-press.mp4"

function demoFor(name){return WALTZ_DEMOS[name]||{primary:["Target muscle"],activation:["Stabilizers"],how:["Set a stable starting position.","Move through a controlled, pain-free range.","Keep the target area working and avoid momentum.","Return slowly to the start."]};}
function targetRegion(primary){const s=primary.join(" ").toLowerCase();if(/quad|hamstring|glute|calf|leg/.test(s))return"LOWER BODY";if(/chest|shoulder|tricep|bicep|back|lat|delt/.test(s))return"UPPER BODY";return"CORE";}
function videoDemo(ex){
 const d=demoFor(ex.name), url=WALTZ_VIDEO_URLS[ex.name], region=targetRegion(d.primary);
 if(url)return `<div class="waltz-video-stage"><div class="demo-stage-label"><span>HOW TO DO IT</span><strong>${escapeHtml(ex.name).toUpperCase()}</strong></div><div class="video-frame"><video class="exercise-video" src="${url}" autoplay muted loop playsinline controls></video></div><div class="demo-legend"><span><i class="green"></i>Primary: ${d.primary.map(escapeHtml).join(" • ")}</span><span><i class="red"></i>Activation: ${d.activation.map(escapeHtml).join(" • ")}</span></div></div>`;
 return `<div class="waltz-video-stage reference-mode"><div class="demo-stage-label"><span>EXERCISE DEMO</span><strong>${escapeHtml(ex.name).toUpperCase()}</strong></div><div class="video-frame reference-frame"><div class="reference-silhouette"><div class="ref-head"></div><div class="ref-body"><span class="ref-primary"></span><span class="ref-tension left"></span><span class="ref-tension right"></span></div><div class="ref-legs"></div></div><div class="reference-overlay"><span class="preview-chip">VIDEO DEMO</span><strong>Motion clip coming next</strong><small>WALTZ anatomical reference • ${region}</small></div></div><div class="demo-legend"><span><i class="green"></i>Primary: ${d.primary.map(escapeHtml).join(" • ")}</span><span><i class="red"></i>Activation: ${d.activation.map(escapeHtml).join(" • ")}</span></div></div>`;
}
function renderSetLogger(ex,workout,key,saved){return `<div class="waltz-log-panel hidden" id="exerciseLogPanel"><div class="player-body"><span class="mini-label">${workout.name}</span><h2>${escapeHtml(ex.name)}</h2><div class="exercise-meta"><span class="badge">${escapeHtml(ex.muscle)}</span><span class="badge">${ex.sets} sets</span><span class="badge">${escapeHtml(ex.reps)} reps</span><span class="badge">Rest ${escapeHtml(ex.rest)}</span></div><div class="set-table">${Array.from({length:ex.sets},(_,s)=>`<div class="set-row"><strong>Set ${s+1}</strong><input inputmode="decimal" placeholder="kg" value="${saved[s]?.weight||""}" id="wt-${s}"><input inputmode="numeric" placeholder="reps" value="${saved[s]?.reps||""}" id="rp-${s}"><button class="${saved[s]?.done?"done":""}" onclick="toggleSet(${s})">${saved[s]?.done?"✓":"Done"}</button></div>`).join("")}</div><div class="player-actions"><button class="secondary" onclick="backToExerciseDemo()">Watch Demo</button><button class="primary" onclick="nextExercise()">Next</button></div></div></div>`;}
function renderGuidedExercise(){const{w,i,e}=state.activeWorkout,workout=state.plan.weeks[w-1].workouts[i],ex=workout.exercises[e],key=`w${w}d${i+1}-${e}`,saved=JSON.parse(localStorage.getItem(key)||"{}"),d=demoFor(ex.name);document.getElementById("playerHost").innerHTML=`<div class="player-card guided-player"><div id="exerciseDemoPanel" class="waltz-demo-panel">${videoDemo(ex)}<div class="player-body demo-copy"><span class="mini-label">${workout.name} • Exercise ${e+1}/${workout.exercises.length}</span><h2>${escapeHtml(ex.name)}</h2><section class="how-card"><h3>How to do it</h3><ol>${d.how.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ol></section><section class="target-card"><h3>Target</h3><div><span class="target-label primary">Primary</span><strong>${d.primary.map(escapeHtml).join(" • ")}</strong></div><div><span class="target-label tension">Activation</span><strong>${d.activation.map(escapeHtml).join(" • ")}</strong></div></section><button class="primary start-exercise-btn" onclick="startLoggedExercise()">Start Exercise</button></div></div>${renderSetLogger(ex,workout,key,saved)}</div>`;}
window.startLoggedExercise=function(){document.getElementById("exerciseDemoPanel")?.classList.add("hidden");document.getElementById("exerciseLogPanel")?.classList.remove("hidden");};
window.backToExerciseDemo=function(){saveSets();document.getElementById("exerciseLogPanel")?.classList.add("hidden");document.getElementById("exerciseDemoPanel")?.classList.remove("hidden");};
window.renderExercise=renderGuidedExercise;
